// @BLOCK:START(Full Artifact)
const vscode = require('vscode');
const path = require('path');
const fs = require('fs');
const resolver = require('./resolver');
const workspace = require('./workspace');

// @BLOCK:START(module-scope)
const state = {
    /** @type {vscode.ExtensionContext | null} */
    context: null,
    /** @type {vscode.OutputChannel | null} */
    outputChannel: null,
    /** @type {Array<{name: string, module: any}>} */
    loadedComponents: [],
};
// @BLOCK:END(module-scope)

// @BLOCK:START(helpers)
/**
 * Validates a returned API object against the interface defined in its manifest.
 * @param {object} api The actual API object returned by a component's initialize function.
 * @param {object} contract The interface contract from the component's manifest.
 * @returns {boolean}
 */
function validateInterface(api, contract) {
    for (const key in contract) {
        if (!(key in api)) {
            throw new Error(`Method '${key}' is missing.`);
        }
        const rule = contract[key];
        if (typeof api[key] !== rule.type) {
            throw new Error(`Method '${key}' should be of type '${rule.type}' but got '${typeof api[key]}'.`);
        }
    }
    return true;
}

/**
 * Generates a .d.ts file from the loaded components' interfaces.
 * @param {string} workspaceRoot
 * @param {Map<string, object>} components
 */
function generateTypeDefinitions(workspaceRoot, components) {
    let typeString = `// THIS FILE IS AUTO-GENERATED BY THE BRIDGE KERNEL. DO NOT EDIT.\n\n`;
    typeString += `interface BridgeContracts {\n`;

    for (const manifest of components.values()) {
        const contract = manifest.provides;
        typeString += `  "${contract}": {\n`;
        for (const key in manifest.interface) {
            // A simple representation for now. Can be expanded later.
            typeString += `    ${key}(...args: any[]): any;\n`;
        }
        typeString += `  };\n`;
    }
    typeString += `}\n`;

    const targetPath = path.join(workspaceRoot, '.bridge', 'contracts.d.ts');
    fs.writeFileSync(targetPath, typeString, 'utf8');
    state.outputChannel?.appendLine(`[Kernel] Type definitions generated at '.bridge/contracts.d.ts'.`);
}
// @BLOCK:END(helpers)

// @BLOCK:START(initialize)
/**
 * Initializes the Bridge component platform.
 * @param {vscode.ExtensionContext} context
 * @param {vscode.OutputChannel} outputChannel
 */
async function initialize(context, outputChannel) {
    state.context = context;
    state.outputChannel = outputChannel;

    const workspaceRoot = workspace.getWorkspaceRoot();
    if (!workspaceRoot || !fs.existsSync(path.join(workspaceRoot, '.bridge', 'config.json'))) {
        vscode.commands.executeCommand('setContext', 'bridge.workspaceInitialized', false);
        outputChannel.appendLine("[Kernel] No .bridge/config.json found. Registering 'initializeWorkspace' command.");
        context.subscriptions.push(
            vscode.commands.registerCommand('bridge.initializeWorkspace', () => {
                workspace.initializeWorkspace(context);
            })
        );
        return;
    }

    vscode.commands.executeCommand('setContext', 'bridge.workspaceInitialized', true);
    outputChannel.appendLine('[Kernel] Initializing component platform...');

    try {
        // 1. Discover all component manifests.
        const components = resolver.discoverComponents(workspaceRoot, outputChannel);
        if (components.size === 0) {
            outputChannel.appendLine('[Kernel] No components found. Initialization complete.');
            return;
        }

        // 2. Build and validate the dependency graph (checks for collisions, missing deps).
        const graph = resolver.buildDependencyGraph(components);

        // 3. Topologically sort the graph (checks for cycles).
        const sortedComponentNames = resolver.topologicalSort(graph);
        outputChannel.appendLine(`[Kernel] Initialization order resolved: ${sortedComponentNames.join(' -> ')}`);

        // 4. Initialize components in order.
        const apiRegistry = new Map();
        for (const name of sortedComponentNames) {
            const manifest = components.get(name);
            const mainPath = path.join(manifest.path, manifest.main);
            
            // Clear cache for clean re-activation
            delete require.cache[require.resolve(mainPath)];
            const module = require(mainPath);

            const deps = {};
            for (const depContract of (manifest.dependsOn || [])) {
                // This is a simplified injection. A real one would be nested.
                // For now, we map contract to api directly.
                deps[depContract] = apiRegistry.get(depContract);
            }

            const api = await module.initialize(deps);
            
            // Validate the returned API against the manifest's interface.
            validateInterface(api, manifest.interface);

            apiRegistry.set(manifest.provides, api);
            state.loadedComponents.push({ name, module });
            outputChannel.appendLine(`[Kernel] > Component '${name}' initialized.`);
        }

        // 5. Generate type definitions for DX.
        generateTypeDefinitions(workspaceRoot, components);

        outputChannel.appendLine('[Kernel] All components initialized successfully.');

    } catch (error) {
        const errorMessage = `Failed to initialize components: ${error.message}`;
        outputChannel.appendLine(`[Kernel] FATAL: ${errorMessage}`);
        vscode.window.showErrorMessage(errorMessage);
    }
}
// @BLOCK:END(initialize)

// @BLOCK:START(deactivate)
/**
 * Deactivates all loaded components in reverse order of initialization.
 */
function deactivate() {
    state.outputChannel?.appendLine('[Kernel] Deactivating components...');
    for (const component of state.loadedComponents.reverse()) {
        if (typeof component.module.deactivate === 'function') {
            try {
                component.module.deactivate();
            } catch (error) {
                state.outputChannel?.appendLine(`[Kernel] Error deactivating component '${component.name}': ${error.message}`);
            }
        }
    }
    // Reset state for clean re-activation
    state.loadedComponents = [];
    state.context = null;
    state.outputChannel = null;
}
// @BLOCK:END(deactivate)

// @BLOCK:START(exports)
module.exports = {
    initialize,
    deactivate,
};
// @BLOCK:END(exports)
// @BLOCK:END(Full Artifact)